hue:
  bridges:
    - host: !secret hue_bridge
      allow_unreachable: true
      allow_hue_groups: false


input_number:
  smoke_break_duration:
    name: Smoke break duration
    icon: mdi:smoking
    mode: slider
    min: 5
    max: 480


# device_tracker:
#   - platform: huesensor


binary_sensor:
  - platform: huesensor


sensor:
  - platform: huesensor

  - platform: template
    sensors:
      temperature_bathroom:
        friendly_name: 'Bathroom Temperature'
        device_class: 'temperature'
        unit_of_measurement: '°C'
        icon_template: 'mdi:thermometer'
        value_template: '{{ states.binary_sensor.bathroom_motion_motion_sensor.attributes.temperature }}'
        entity_id: binary_sensor.bathroom_motion_motion_sensor
      temperature_hallway:
        friendly_name: 'Hallway Temperature'
        device_class: 'temperature'
        unit_of_measurement: '°C'
        icon_template: 'mdi:thermometer'
        value_template: '{{ states.binary_sensor.hallway_motion_motion_sensor.attributes.temperature }}'
        entity_id: binary_sensor.hallway_motion_motion_sensor
      temperature_kitchen:
        friendly_name: 'Kitchen Temperature'
        device_class: 'temperature'
        unit_of_measurement: '°C'
        icon_template: 'mdi:thermometer'
        value_template: '{{ states.binary_sensor.kitchen_motion_motion_sensor.attributes.temperature }}'
        entity_id: binary_sensor.kitchen_motion_motion_sensor
      temperature_toilet:
        friendly_name: 'Toilet Temperature'
        device_class: 'temperature'
        unit_of_measurement: '°C'
        icon_template: 'mdi:thermometer'
        value_template: '{{ states.binary_sensor.toilet_motion_motion_sensor.attributes.temperature }}'
        entity_id: binary_sensor.toilet_motion_motion_sensor

#   - platform: command_line
#     name: 'Hue Toilet Battery'
#     command: /scripts/zhue.sh battery toilet
#     value_template: '{{ value_json.config.battery }}'
#     unit_of_measurement: '%'
#     # scan_interval: 3600
#
#   - platform: command_line
#     name: 'Hue Toilet Lux'
#     command: /scripts/zhue.sh lux toilet
#     value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
#     unit_of_measurement: klx
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Toilet Temperature'
#     command: /scripts/zhue.sh temperature toilet
#     value_template: '{{ value_json.state.temperature | float / 100 }}'
#     unit_of_measurement: °C
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Hallway Battery'
#     command: /scripts/zhue.sh battery hallway
#     value_template: '{{ value_json.config.battery }}'
#     unit_of_measurement: '%'
#     # scan_interval: 3600
#
#   - platform: command_line
#     name: 'Hue Hallway Lux'
#     command: /scripts/zhue.sh lux hallway
#     value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
#     unit_of_measurement: klx
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Hallway Temperature'
#     command: /scripts/zhue.sh temperature hallway
#     value_template: '{{ value_json.state.temperature | float / 100 }}'
#     unit_of_measurement: °C
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Kitchen Battery'
#     command: /scripts/zhue.sh battery kitchen
#     value_template: '{{ value_json.config.battery }}'
#     unit_of_measurement: '%'
#     # scan_interval: 3600
#
#   - platform: command_line
#     name: 'Hue Kitchen Lux'
#     command: /scripts/zhue.sh lux kitchen
#     value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
#     unit_of_measurement: klx
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Kitchen Temperature'
#     command: /scripts/zhue.sh temperature kitchen
#     value_template: '{{ value_json.state.temperature | float / 100 }}'
#     unit_of_measurement: °C
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Bathroom Battery'
#     command: /scripts/zhue.sh battery bathroom
#     value_template: '{{ value_json.config.battery }}'
#     unit_of_measurement: '%'
#     # scan_interval: 3600
#
#   - platform: command_line
#     name: 'Hue Bathroom Lux'
#     command: /scripts/zhue.sh lux bathroom
#     value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
#     unit_of_measurement: klx
#     # scan_interval: 600
#
#   - platform: command_line
#     name: 'Hue Bathroom Temperature'
#     command: /scripts/zhue.sh temperature bathroom
#     value_template: '{{ value_json.state.temperature | float / 100 }}'
#     unit_of_measurement: °C
#     # scan_interval: 600
#
#
# binary_sensor:
#   - platform: command_line
#     name: 'Toilet Presence'
#     device_class: motion
#     command: /scripts/zhue.sh presence toilet
#     value_template: '{{ value_json.state.presence }}'
#     payload_on: "True"
#     payload_off: "False"
#     scan_interval: 1
#
#   - platform: command_line
#     name: 'Hallway Presence'
#     device_class: motion
#     command: /scripts/zhue.sh presence hallway
#     value_template: '{{ value_json.state.presence }}'
#     payload_on: "True"
#     payload_off: "False"
#     scan_interval: 1
#
#   - platform: command_line
#     name: 'Kitchen Presence'
#     device_class: motion
#     command: /scripts/zhue.sh presence kitchen
#     value_template: '{{ value_json.state.presence }}'
#     payload_on: "True"
#     payload_off: "False"
#     scan_interval: 1
#
#   - platform: command_line
#     name: 'Bathroom Presence'
#     device_class: motion
#     command: /scripts/zhue.sh presence bathroom
#     value_template: '{{ value_json.state.presence }}'
#     payload_on: "True"
#     payload_off: "False"
#     scan_interval: 1


group:
  hue_lights:
    name: Hue Lights
    view: no
    entities:
      - light.hue_bathroom
      - light.hue_bedroom
      - light.hue_front_door
      - light.hue_hallway
      - light.hue_kitchen
      - light.hue_living_room_table
      - light.hue_living_room_tv
      - light.hue_office
      - light.hue_terrace
      - light.hue_toilet


scene:
  - name: Living Room Normal
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 150
        xy_color: [ 0.4448, 0.4066 ]

  - name: Living Room Dim
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 75
        xy_color: [ 0.5926, 0.3814 ]
      light.hue_front_door:
        state: off
        transition: 1
      light.hue_terrace:
        state: off
        transition: 1
      light.hue_kitchen:
        state: off
        transition: 1

  - name: Flash Living Room Lights
    entities:
      light.living_room:
        state: on
        flash: short

  - name: Flash Office Lights
    entities:
      light.hue_office:
        state: on
        flash: short

  - name: Flash Lights
    entities:
      light.hue_office:
        state: on
        flash: short
      light.living_room:
        state: on
        flash: short

  - name: Bedtime
    entities:
      light.hue_terrace:
        state: off
      light.hue_hallway:
        state: off
      light.hue_toilet:
        state: off
      light.bathroom:
        state: off
      light.hue_office:
        state: off
      light.hue_bedroom:
        state: off


script:
  flash_office_lights:
    alias: Flash Office Lights
    sequence:
      - service: scene.turn_on
        entity_id: scene.flash_office_lights

  flash_living_room_lights:
    alias: Flash Living Room Lights
    sequence:
      - service: scene.turn_on
        entity_id: scene.flash_living_room_lights

  flash_lights:
    alias: Flash Lights
    sequence:
      - service: script.flash_living_room_lights
      - service: script.flash_office_lights

  smoke_break:
    alias: "Smoke break"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
          entity_id: script.smoke_break_timer_off
      - service_template: >
          light.{% if is_state('light.hue_terrace', 'on') %}turn_off{% else %}turn_on{% endif %}
        data:
          entity_id: light.hue_terrace
          color_name: white
          brightness: 217 # 85%
          # {% if is_state('light.hue_terrace', 'on') %}
          # color_name: white
          # brightness: 217 # 85%
          # {% endif %}
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.smoke_break_timer_off

  smoke_break_timer_off:
    alias: "Smoke break: Turn off lamp after X minutes"
    sequence:
      - delay: '00:{{ states.input_number.smoke_break_duration.state|int }}:00'
      - service: light.turn_off
        data:
          entity_id: light.hue_terrace


automation:
  - alias: Turn off bedroom lights after 30 minutes
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bedroom
        to: 'on'
        for:
          minutes: 30
    action:
      - service: light.turn_off
        entity_id: light.hue_bedroom

  - alias: Turn off front door lights after 30 minutes
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_front_door
        to: 'on'
        for:
          minutes: 30
    action:
      - service: light.turn_off
        entity_id: light.hue_front_door

  - alias: Hue Master Switch ON pressed
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.master_dimmer_switch
        to: 1_hold
      - platform: state
        entity_id: sensor.master_dimmer_switch
        to: 1_hold_up
    action:
      - service: script.open_all_covers
      - service: script.watch_tv

  - alias: Hue Master Switch OFF pressed
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.master_dimmer_switch
        to: 4_hold
      - platform: state
        entity_id: sensor.master_dimmer_switch
        to: 4_hold_up
    action:
      - service: script.all_off

  - alias: Hue Living Room Switch ON long pressed
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.living_room_dimmer_switch
        to: 1_hold
      - platform: state
        entity_id: sensor.living_room_dimmer_switch
        to: 1_hold_up
    action:
      - service: script.open_living_room_covers

  - alias: Hue Living Room Switch OFF long pressed
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.living_room_dimmer_switch
        to: 4_hold
      - platform: state
        entity_id: sensor.living_room_dimmer_switch
        to: 4_hold_up
    action:
      - service: script.close_living_room_covers


homeassistant:
  customize:
    light.hue_bedroom:
      icon: mdi:hotel
    light.hue_front_door:
      icon: mdi:door-closed
    light.hue_hallway:
      icon: mdi:floor-plan
    light.hue_kitchen:
      icon: mdi:pot-mix
    light.hue_living_room_table:
      icon: mdi:seat-legroom-extra
    light.hue_living_room_tv:
      icon: mdi:television-box
    light.hue_office:
      icon: mdi:alpha-o-box
    light.hue_terrace:
      icon: mdi:alpha-t-box
    light.hue_toilet:
      icon: mdi:human-male-female
    # Hue sensors
    sensor.living_room_dimmer_switch:
      icon: mdi:light-switch
    sensor.master_dimmer_switch:
      icon: mdi:light-switch
    sensor.hallway_lux:
      icon: mdi:white-balance-sunny
    sensor.toilet_lux:
      icon: mdi:white-balance-sunny
    sensor.kitchen_lux:
      icon: mdi:white-balance-sunny
    sensor.bathroom_lux:
      icon: mdi:white-balance-sunny
    sensor.home_temperature:
      icon: mdi:temperature-celsius
    # Scenes
    scene.bedtime:
      icon: mdi:weather-night
      order: 1
    scene.living_room_normal:
      icon: mdi:brightness-1
    scene.living_room_dim:
      icon: mdi:brightness-2
    # Scripts
    script.flash_living_room_lights:
      icon: mdi:spotlight
    script.smoke_break:
      icon: mdi:smoking

# vim: set filetype=yaml et sw=2 ts=2 :
