version: '3.4'

services:
  hass:
    image: homeassistant/home-assistant:latest
    container_name: hass
    restart: unless-stopped
    depends_on:
      - database
    network_mode: host
    cap_add:
      - NET_ADMIN  # Required for adding new routes
    extra_hosts:
      - "hass-db:172.92.92.92"
      - "mqtt:172.92.92.95"
    volumes:
      - ./certs:/certs:ro
      - ./config/hass:/config
      - ./data/log:/log
      - ./scripts:/scripts:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pschmitt/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    healthcheck:
      test: "curl -Lf http://localhost:8123"
      start_period: 6m
      timeout: 15s
      interval: 30s
      retries: 3
    labels:
      # Traefik v2
      # - "traefik.enable=true"
      # - "traefik.http.routers.hass-http.entrypoints=http"
      # - "traefik.http.routers.hass-http.rule=Host(`home.comreset.io`)"
      # - "traefik.http.routers.hass-http.middlewares=tls-redirect@file"
      # - "traefik.http.routers.hass-https.entrypoints=https"
      # - "traefik.http.routers.hass-https.rule=Host(`home.comreset.io`)"
      # - "traefik.http.routers.hass-https.tls=true"
      # - "traefik.http.routers.hass-https.tls.certresolver=le"
      # - "traefik.http.routers.hass-https.service=hass"
      # - "traefik.http.services.hass.loadbalancer.server.port=8123"
      - "traefik.enable=true"
      - "traefik.backend=home-assistant"
      - "traefik.frontend.rule=Host:home.comreset.io,heimat.dev,hass.heimat.dev"
      - "traefik.port=8123"
      - "com.centurylinklabs.watchtower.enable=false"
      - "autoheal=true"

  database:
    image: postgres:9
    container_name: hass-db
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.92.92.92
    env_file:
      - postgres.env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      test: "su postgres -c pg_isready"

  influxdb:
    image: influxdb
    container_name: hass-influxdb
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.92.92.93
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    env_file:
      - influxdb.env

  grafana:
    image: grafana/grafana
    container_name: hass-grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3000/tcp
    networks:
      backend:
        ipv4_address: 172.92.92.94
    env_file:
      - grafana.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:graphs.home.comreset.io"
      - "traefik.port=3000"

  lego:
    image: xenolf/lego
    environment:
      - CF_API_EMAIL=philipp@schmitt.co
      - CF_API_KEY=***REMOVED***
    volumes:
      - ./data/lego:/data
    command: >
      --path /data
      --accept-tos
      --email="philipp@schmitt.co"
      --domains="mqtt.comreset.io"
      --dns="cloudflare"
      renew --days 30

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./config/mqtt:/mosquitto/config:ro
      - ./data/mqtt:/mosquitto/data
      - ./data/lego/certificates:/certs:ro
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      backend:
        ipv4_address: 172.92.92.95

  appdaemon:
    image: acockburn/appdaemon
    restart: unless-stopped
    ports:
      - 5050:5050
    volumes:
      - ./config/appdaemon:/conf

  nodered:
    image: nodered/node-red-docker:v8
    restart: unless-stopped
    ports:
      - 1880:1880
      - 9229:9229
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/nodered:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nodered"
      - "traefik.frontend.rule=Host:nodered.home.comreset.io"
      - "traefik.port=1880"

  # facebox:
  #   image: machinebox/facebox
  #   restart: unless-stopped
  #   ports:
  #     - 8890:8080
  #   env_file:
  #     - facebox.env

  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.92.92.0/24

# vim: set ft=yaml et ts=2 sw=2 :
