group:
  main_mobile_devices:
    name: Main Devices
    view: no
    icon: mdi:cellphone-android
    entities:
      - group.pschmitt_location

  pschmitt_location:
    name: "pschmitt location"
    view: no
    icon: mdi:cellphone-android
    entities:
      # - device_tracker.google_maps_111748235994603810778
      # - group.g4p
      # - group.ph1
      - group.m2s

  ph1:
    name: "ph1"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.pschmitt_ph1
      - device_tracker.ph1_arp
      - device_tracker.ph1_ping

  n5x:
    name: "n5x"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.n5x_arp
      - device_tracker.n5x_ping

  m2s:
    name: "m2s"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.m2s_arp
      - device_tracker.m2s_ping

  g4p:
    name: "g4p"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.g4p_arp
      - device_tracker.g4p_ping

  anika:
    name: "Anika"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.anika_iphone
      - device_tracker.anika_tablet

# vim: set filetype=yaml et sw=2 ts=2 :
