aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2


camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'


alarm_control_panel:
  - platform: aarlo
    home_mode_name: night
    away_mode_name: armed
    trigger_time: 30
    alarm_volume: 8


binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength


light:
  - platform: aarlo


media_player:
  - platform: aarlo


switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    siren_volume: 1
    siren_duration: 10


automation:
  - alias: Update Arlo Camera snapshot every 4h
    initial_state: true
    trigger:
      - platform: time_pattern
        hours: 4
    action:
      - service: camera.aarlo_request_snapshot
        data:
          entity_id: camera.aarlo_front_door
      - service: camera.aarlo_request_snapshot
        data:
          entity_id: camera.aarlo_hallway
      - service: camera.aarlo_request_snapshot
        data:
          entity_id: camera.aarlo_terrace

  - alias: Update Arlo Camera snapshot every 3s when recording
    initial_state: true
    trigger:
      - platform: state
        entity_id: camera.aarlo_hallway, camera.aarlo_front_door, camera.aarlo_terrace
        from: 'idle'
        to: 'recording'
        for: 00:00:03
      - platform: state
        entity_id: camera.aarlo_hallway, camera.aarlo_front_door, camera.aarlo_terrace
        from: 'recently active'
        to: 'recording'
        for: 00:00:03
    action:
      - service: camera.aarlo_request_snapshot
        data_template:
          entity_id: "{{ trigger.entity_id }}"

# vim: set filetype=yaml et sw=2 ts=2 :
