sensor:
  # Public IPv4
  - platform: dnsip

  - platform: rest
    name: IP Location
    resource: https://ifconfig.co/json
    value_template: '{{ value_json.country }}'

  - platform: template
    sensors:
      ip_location_short:
        friendly_name: WAN IP
        value_template: '{{ states.sensor.myip.state }} ({{ states.sensor.ip_location.state }})'


binary_sensor:
  - platform: template
    sensors:
      vpn_state:
        value_template: '{{ states.sensor.ip_location.state != "France" }}'
        friendly_name: 'VPN State'


alert:
  ip_location:
    name: IP Location
    entity_id: sensor.vpn_state
    state: 'off'
    repeat: 60
    can_acknowledge: True
    skip_first: False
    notifiers:
      - html5


homeassistant:
  customize:
    sensor.myipopendnscom:
      icon: mdi:network
      friendly_name: WAN IP
    sensor.ip_location:
      icon: mdi:map-marker
    sensor.ip_location_short:
      icon: mdi:map-marker

# vim: set filetype=yaml et sw=2 ts=2 :
