lock:
  - platform: nuki
    host: !secret nuki_bridge
    token: !secret nuki_token


script:
  lock_door:
    alias: Lock door
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.front_door

  lock_door_if_not_open:
    alias: Lock door
    sequence:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_front_door
        state: 'off'
      - service: script.lock_door

  unlock_door:
    alias: Unlock door
    sequence:
      - service: lock.unlock
        data:
          entity_id: lock.front_door

  lock_n_go:
    alias: Lock'n'go
    sequence:
      - service: lock.nuki_lock_n_go
        data:
          entity_id: lock.front_door


automation:
  - alias: Lock door after 15min
    initial_state: true
    trigger:
      platform: state
      entity_id: lock.front_door
      to: 'unlocked'
      for:
        minutes: 10
    action:
      - service: script.lock_door_if_not_open

  - alias: "HTML5 notification: Close door"
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: lock_door
    action:
      - service: script.lock_door

  - alias: "Nuki Webhook"
    initial_state: true
    trigger:
      - platform: webhook
        webhook_id: !secret nuki_webhook
    action:
      - service: notify.html5
        data_template:
          message: "Nuki webhook: {{ trigger.json }}"
          data:
            tag: "nuki-webhook"
      - service: python_script.set_state
        data_template:
          entity_attr:
            nuki_id: '{{ trigger.json.nukiId }}'
          state: '{{ trigger.json.stateName }}'
          # Attributes
          battery_critical: '{{ trigger.json.batteryCritical }}'
          updated_by: python_script.set_state

alert:
  door_open:
    name: "The door is unlocked. Want me to lock it?"
    entity_id: lock.front_door
    state: 'unlocked'
    repeat: 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - door_is_open


notify:
  - name: door_is_open
    platform: group
    services:
      - service: html5
        data:
          message: "The door is unlocked. Want me to lock it?"
          data:
            tag: 'lock-door-query'
            renotify: True
            actions:
              - action: lock_door
                icon: https://materialdesignicons.com/api/download/icon/png/D711AFDE-2B8D-4932-82AC-A04E7B2810AE/48
                title: "Lock it"


homeassistant:
  customize:
    lock.front_door:
      icon: mdi:lock-smart
      friendly_name: Front Door Lock
    # Scripts
    script.lock_n_go:
      icon: mdi:run-fast
    script.lock_door:
      icon: mdi:lock
    script.unlock_door:
      icon: mdi:lock-open-outline

# vim: set filetype=yaml et sw=2 ts=2 :
