octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1


sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage


binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

  - platform: command_line
    name: Rendering timelapse
    device_class: moving
    command: !secret cmd_octoprint_timelapse_rendering
    payload_on: "running"
    payload_off: "not running"


switch:
  - platform: command_line
    switches:
      3d_printer_led:
        friendly_name: "3D Printer LED"
        command_on: !secret cmd_octoprint_led_on
        command_off: !secret cmd_octoprint_led_off


light:
  - platform: template
    lights:
      3d_printer_led:
        friendly_name: "3D Printer LED"
        icon_template: mdi:printer-3d
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.3d_printer_led
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.3d_printer_led


camera:
  - platform: mjpeg
    name: octoprint
    mjpeg_url: !secret octoprint_camera_url


group:
  3d_printer:
    name: 3D Printer
    view: no
    control: hidden
    entities:
      - switch.3d_printer
      - light.3d_printer_led
      - camera.octoprint
      - sensor.octoprint_current_state
      - binary_sensor.octoprint_printing
      - binary_sensor.rendering_timelapse
      - sensor.octoprint_job_percentage


script:
  turn_off_3d_printer:
    sequence:
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: 'off'
      - service: switch.turn_off
        entity_id: switch.3d_printer


automation:
  - alias: Notify when the current 3D print has finished
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.octoprint_printing
      from: "on"
      to: "off"
    condition:
      condition: template
      value_template: "{{ not is_state('sensor.octoprint_current_state', 'Paused') }}"
    action:
      - service: notify.html5
        data:
          message: "3D Print finished"
          data:
            tag: "3d_print_finished"
      # - delay: '00:05:00'
      # - service: group.set_visibility
      #   entity_id: group.3d_printer
      #   data:
      #     visible: False

  - alias: Notify when the current 3D print has errored out
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.octoprint_printing_error
      from: "off"
      to: "on"
    action:
      - service: notify.html5
        data:
          message: "Woops! The 3D print has failed..."
          data:
            tag: "3d_print_failed"

  - alias: Turn on lights if the sun goes down and there is an ongoing print
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.octoprint_printing
          state: "on"
        - condition: state
          entity_id: light.yeelight_office
          state: "off"
    action:
      - service: notify.html5
        data:
          message: "Turning office lights on so that the timelapse does not get fucked."
          data:
            tag: "3d_print_nighttime_light"
      - service: light.turn_on
        data:
          entity_id: light.yeelight_office

  - alias: Notify when the timelapse has finished rendering
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.rendering_timelapse
      from: "on"
      to: "off"
    action:
      - service: notify.html5
        data:
          message: "3D printing timelapse rendering has ended"
          data:
            tag: "3d_print_timelapse_rendered"


homeassistant:
  customize:
    binary_sensor.octoprint_printing:
      icon: mdi:printer-3d

# vim: set filetype=yaml et sw=2 ts=2 :
