switch:
  - platform: mqtt
    name: "3D Printer PSU"
    icon: mdi:printer-3d
    # state_topic: hassistant/states/switch/pollin_s4u3/state
    command_topic: hassistant/remote/switch/pollin
    payload_on: >-
      {"command": "on", "system_code": "4", "unit_code": "4" }
    payload_off: >-
      {"command": "off", "system_code": "4", "unit_code": "4" }

  - platform: mqtt
    name: "Office Monitor"
    icon: mdi:monitor
    # state_topic: hassistant/states/switch/pollin_s4u4/state
    command_topic: hassistant/remote/switch/pollin
    payload_on: >-
      {"command": "on", "system_code": "4", "unit_code": "3" }
    payload_off: >-
      {"command": "off", "system_code": "4", "unit_code": "3" }


#   - platform: template
#     switches:
#       3d_printer_psu:
#         value_template: ""  # FIXME
#         turn_on:
#           service: script.toggle_pollin_switch
#           data:
#             command: "on"
#             system_code: "4"
#             unit_code: "3"
#         turn_off:
#           service: script.toggle_pollin_switch
#           data:
#             command: "off"
#             system_code: "4"
#             unit_code: "3"


sensor:
  - platform: mqtt
    name: "Freezer Temperature"
    state_topic: "hassistant/states/sensor/telldus_ft007th_temperature/state"
    device_class: temperature
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Freezer Temperature - last updated"
    state_topic: "hassistant/states/sensor/telldus_ft007th_humidity/last_updated"

  - platform: mqtt
    name: "Freezer Temperature - last changed"
    state_topic: "hassistant/states/sensor/telldus_ft007th_humidity/last_changed"

  - platform: mqtt
    name: "Freezer Humidity"
    state_topic: "hassistant/states/sensor/telldus_ft007th_humidity/state"
    device_class: humidity
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Freezer Battery"
    state_topic: "hassistant/states/sensor/telldus_ft007th_temperature/Battery numeric"
    device_class: battery
    unit_of_measurement: "%"

# script:
#   toggle_pollin_switch:
#     alias: 'Turn a pollin switch on or off'
#     sequence:
#       - service: mqtt.publish
#         data_template:
#           topic: hassistant/remote/switch/pollin
#           payload: >-
#             '{"command": "{{ payload }}", "system_code": "{{ system_code }}", "unit_code": "{{ unit_code}}" }'


homeassistant:
  customize:
    switch.3d_printer_psu:
      assumed_state: false
    switch.ac:
      assumed_state: false

# vim: set filetype=yaml et sw=2 ts=2 :
