light:
  - platform: template
    lights:
      bathroom_mirror:
        friendly_name: "Bathroom Mirror Light"
        availability_template: >-
          '{{ not is_state("switch.sonoff_bathroom_mirror_light_relay", "unavailable") }}'
        value_template: '{{ states("switch.sonoff_bathroom_mirror_light_relay") }}'
        icon_template: mdi:spotlight
        turn_on:
          service: switch.turn_on
          entity_id: switch.sonoff_bathroom_mirror_light_relay
        turn_off:
          service: switch.turn_off
          entity_id: switch.sonoff_bathroom_mirror_light_relay


automation:
  - alias: Sync state of bathroom mirror light with bathroom light (ON)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bathroom
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bathroom_mirror

  - alias: Sync state of bathroom mirror light with bathroom light (OFF)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bathroom
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bathroom_mirror

  - alias: Turn kitchen hood back on after 1 minute to avoid service interruption
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.sonoff_kitchen_hood_relay
        to: 'off'
        for:
          minutes: 1
    action:
      service: switch.turn_on
      entity_id: switch.sonoff_kitchen_hood_relay

# vim: set filetype=yaml et sw=2 ts=2 :
