sensor:
  - platform: command_line
    name: Torrent IP
    command: "/scripts/get_torrent_ip.py nasteanas.lan"


binary_sensor:
  - platform: template
    sensors:
      vpn:
        friendly_name: VPN OK
        value_template: "{{ states('sensor.torrent_ip') == states('sensor.myipopendnscom') }}"
        entity_id:
          - sensor.torrent_ip
          - sensor.myipopendnscom
        device_class: problem


transmission:
  host: 10.7.0.216

# vim: set filetype=yaml et sw=2 ts=2 :
