meteo_france:
  - city: !secret postal_code
    monitored_conditions:
      - rain_chance
      - freeze_chance
      - thunder_chance
      - snow_chance
      - weather
      - next_rain
      - wind_speed
      - temperature
      - uv

weather:
  - platform: darksky
    name: darksky
    api_key: !secret darksky_api_key
    mode: daily

  - platform: openweathermap
    api_key: !secret openweathermap_api_key

  - platform: yweather


sensor:
  - platform: yr
    monitored_conditions:
      - symbol

  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - alerts
      - feelslike_c
      - feelslike_string
      - precip_1d
      - precip_today_metric
      - precip_today_string
      - temp_c
      - weather
      - weather_1d_metric
      - weather_2d_metric
      - wind_string

  - platform: darksky
    api_key: !secret darksky_api_key
    scan_interval: '00:05:00'
    forecast:
      - 0
      - 1
      - 2
    monitored_conditions:
      # - nearest_storm_bearing
      # - nearest_storm_distance
      # - ozone
      # - pressure
      # - visibility
      # - wind_bearing
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - cloud_cover
      - daily_summary
      - dew_point
      - hourly_summary
      - humidity
      - icon
      - minutely_summary
      - precip_intensity
      - precip_intensity_max
      - precip_probability
      - precip_type
      - summary
      - temperature
      - temperature_high
      - temperature_low
      - wind_speed

  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    language: en
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow


group:
  weather:
    name: Weather
    entities:
      - group.weather_indoor
      - group.weather_outdoor

  weather_shortcut:
    name: Weather
    entities:
      - weather.darksky
      - sensor.pws_weather_2d_metric
      - sensor.home_temperature

  weather_indoor:
    name: Weather
    entities:
      - sensor.hue_bathroom_temperature
      - sensor.hue_hallway_temperature
      - sensor.hue_kitchen_temperature
      - sensor.hue_toilet_temperature
      - sensor.fibaro_system_fgsd002_smoke_sensor_temperature

  weather_outdoor:
    name: Weather
    entities:
      - sensor.yr_symbol
      - sensor.owm_temperature
      - sensor.owm_rain


automation:
  - alias: Exterior temperature is above home temperature
    initial_state: true
    trigger:
      - platform: template
        value_template: '{{ states("sensor.home_temperature") > states("sensor.temperature_terrace") }}'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.main_mobile_devices
          state: "home"
        - condition: numeric_state
          entity_id: sensor.home_temperature
          above: 21
        - condition: time
          after: '10:00:00'
          before: '22:00:00'
    action:
      service: notify.html5
      data_template:
        message: 'You can open the windows now! Indoor: {{ states("sensor.home_temperature") }} - Outdoor: {{ states("sensor.temperature_terrace") }}'
        data:
          tag: "safe-to-open-window"


homeassistant:
  customize:
    sensor.owm_rain:
      icon: mdi:weather-rainy
    sensor.own_rain:
      icon: mdi:weather-rainy

# vim: set filetype=yaml et sw=2 ts=2 :
