withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_consumer_secret
  profiles:
    - Philipp_Schmitt

automation:
  - alias: "Notify when in bed"
    initial_state: true
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          component: "withings"
          event: "in_bed"
    action:
      - service: notify.html5
        data_template:
          message: '{{ trigger.event.data.user }} is in bed'
          data:
            tag: 'withings-in-bed'
      - service: input_boolean.turn_on
        entity_id: input_boolean.bed_occupied
      # - service: device_tracker.see
      #   data_template:
      #     host_name: 'withings_sleep'
      #     dev_id: 'withings_sleep'
      #     mac: '{{ trigger.event.data.user }}'
      #     location_name: 'bed'

  - alias: "Notify when out of bed"
    initial_state: true
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          component: "withings"
          event: "out_of_bed"
    action:
      - service: notify.html5
        data_template:
          message: '{{ trigger.event.data.user }} got out of bed'
          data:
            tag: 'withings-out-of-bed'
      - service: input_boolean.turn_off
        entity_id: input_boolean.bed_occupied
      # - service: device_tracker.see
      #   data_template:
      #     host_name: 'withings_sleep'
      #     dev_id: 'withings_sleep'
      #     mac: '{{ trigger.event.data.user }}'
      #     location_name: 'bed'

# TODO: Bed presence sensor! template device tracker?

input_boolean:
  bed_occupied:
    name: Bed occupied
    icon: mdi:bed

# vim: set ft=yaml et ts=2 sw=2 :
