homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 10.7.0.0/24

http:
  base_url: !secret base_url
  server_port: 8123
  login_attempts_threshold: 20
  use_x_forwarded_for: true
  trusted_proxies:
    # Traefik
    - 127.0.0.1
    - 10.7.0.1

config:
conversation:
discovery:
downloader: !include downloader.yaml
group: !include_dir_merge_named groups
history:
local_ip:
logbook:
lovelace:
  mode: yaml
map:
mobile_app:
recorder:
  purge_interval: 1
  purge_keep_days: 2
  db_url: !secret db_url
sensor: !include sensor.yaml
sun:
system_health:
updater:

# vim: set filetype=yaml et sw=2 ts=2 :
