resources:
  - url: /local/cards/custom-lovelace/plan-coordinates/plan-coordinates.js?v=0.1.0
    type: js
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js?v=1.5.2
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
    type: module

custom_header:
  compact_mode: true

name: Home Assistant
views:
  - !include lovelace/main.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/media.yaml
  - !include lovelace/cctv.yaml
  - !include lovelace/data.yaml
  - !include lovelace/debug.yaml
  - !include lovelace/settings.yaml

# vim: set filetype=yaml et sw=2 ts=2 :
